# Generated by Django 3.0.2 on 2020-10-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_marathon', '0003_auto_20201014_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='udemy',
            field=models.BooleanField(default=True),
        ),
    ]
