# Generated by Django 3.0.2 on 2020-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_marathon', '0004_learningsession_udemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='udemy',
            field=models.BooleanField(default=False),
        ),
    ]
